export const site = {
  name: 'Cheng-I Jeff Lai',
  short: 'Jeff Lai',
  role: 'Speech Researcher',
  /** Shown under the name in the sidebar on every page — kept here so the
      homepage and the blog can't drift apart. */
  tagline:
    'Speech Researcher at <a href="https://ai.meta.com/">Meta Superintelligence Labs</a> — building <strong>speech-to-speech LLMs</strong>.',
  org: 'Meta Superintelligence Labs',
  orgUrl: 'https://ai.meta.com/',
  email: 'jefflai108@gmail.com',
  url: 'https://jefflai108.github.io',
  // The portrait is imported from src/assets/ so Astro content-hashes the
  // filename; a swapped photo can't be hidden behind a stale browser cache.
  /**
   * Generated by scripts/build-cv.py, which strips the phone number from the
   * private résumé and refuses to write a file that still contains one.
   * Never hand-copy a résumé PDF here — regenerate it through that script.
   */
  cv: '/data/cv.pdf',
  links: {
    scholar: 'https://scholar.google.com/citations?user=mV4mRm0AAAAJ&hl=en',
    github: 'https://github.com/jefflai108',
    /**
     * Empty on purpose — the sidebar link only renders when this is set.
     *
     * linkedin.com/in/jefflai108/ returns a hard 404 ("Profile Not Found") to
     * logged-out visitors, verified against a control profile that resolves.
     * Set this to the working vanity URL to bring the link back.
     */
    linkedin: '',
    medium: 'https://medium.com/@jefflai108',
  },
  scholarStats: {
    citations: '3,600+',
    hIndex: 18,
    i10: 21,
    asOf: 'Aug 2026',
  },
} as const;

/**
 * Canonical outbound URLs, kept in one place so links stay consistent.
 * All checked to resolve as of Aug 2026.
 *
 * Note: waveforms.ai no longer resolves (NXDOMAIN) after the Meta acquisition,
 * so there is deliberately no `waveforms` homepage here — the acquisition
 * coverage is linked instead.
 */
export const orgs = {
  meta: 'https://ai.meta.com/',
  metaFair: 'https://ai.meta.com/research/',
  waveformsNews: 'https://techcrunch.com/2025/08/08/meta-acquires-ai-audio-startup-waveforms/',
  deepmind: 'https://deepmind.google/',
  apple: 'https://machinelearning.apple.com/',
  mitIbm: 'https://mitibm.mit.edu/',
  amazon: 'https://www.amazon.science/',
  mit: 'https://www.mit.edu/',
  csail: 'https://www.csail.mit.edu/',
  sls: 'https://sls.csail.mit.edu/',
  jhu: 'https://www.jhu.edu/',
  clsp: 'https://www.clsp.jhu.edu/',
  edinburgh: 'https://www.cstr.ed.ac.uk/',
  nii: 'https://www.nii.ac.jp/en/',
} as const;

export const people = {
  glass: 'https://people.csail.mit.edu/jrg/',
  // JHU faculty pages sit behind Cloudflare and answer 403 to bots; they are
  // fine in a browser.
  dehak: 'https://engineering.jhu.edu/faculty/najim-dehak/',
  villalba: 'https://engineering.jhu.edu/faculty/jesus-villalba/',
  king: 'https://homepages.inf.ed.ac.uk/simonk/',
  yamagishi: 'https://yamagishilab.jp/',
} as const;
